# -*- coding: utf-8 -*-
"""Sending-Emails-in-bulk

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vF5iSrHH0b38SS0Ok9T9HiJ4XIhXKjZ0
"""

import pandas as pd
import smtplib

SenderAddress = "xyz"
password = "xyz"

e = pd.read_excel("Email.xlsx")
emails = e['Emails'].values
server = smtplib.SMTP("smtp.gmail.com", 587)
server.starttls()
server.login(SenderAddress, password)
msg = "Hello this is a email form python"
subject = "Hello world"
body = "Subject: {}\n\n{}".format(subject,msg)
for email in emails:
    server.sendmail(SenderAddress, email, body)
server.quit()